### ISSUE TITLE
Lab 1? 

### ISSUE THREAD

**Issue by no-lex** [keirashea/phys-measurement#1]
Is there something I can review?

**Comment by no-lex** [comment]
@keirashea ping

**Comment by keirashea** [comment]
Sorry. I was traveling all this weekend for Canadian Thanksgiving and I
didn't have a lot of time connected to the internet so I've just had to
turn in the assignment without any comments. It also doesn't help that for
most of it I had no idea what I was doing so I really needed to google
pretty much every step. This is just a this weekend thing and everything
should go a lot smoother on my end going forward.

**Comment by no-lex** [comment]
No problem, i'll do a quick review now then. You can probably ask for a little leniency to do changes on Monday morning; it probably won't get graded anyways until at least Monday afternoon.
